# ----
# Site

title: Just a Byte
url: "https://justabyteblog.com"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: A blog about bytes, bites, and a bit of everything else.
author:
  name: Eve Kirkendall
  email: kirkendall.eve@gmail.com
  twitter: justabyteblog # twitter username without the @ symbol
social:
  name: Just a Byte Blog
  links:
    - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
      push_sidebar_down: true
  -
    scope:
      path: "index.html"
    values:
      layout: "home"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Instagram
  - Twitter

_options:
  author_image:
    width: 400
    height: 400
